[package]
name = "rust-utils"
version = "0.1.0"
edition = "2021"

# dEteRmInIsTic

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
textwrap = "0.13.4"
unicode-width ="0.1.10"